# Generated by Django 3.1.5 on 2021-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('resources', models.URLField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
